services:
  - type: web
    name: notes-generator-app
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: notes-generator-db
          property: connectionString

  - type: pserv
    name: notes-generator-db
    env: postgresql
    plan: free
    ipAllowList: []
